### ISSUE TITLE
rails asset:precompile attempts to connect to DB because of globalize

### ISSUE THREAD

**Issue by ismaelga** [globalize/globalize#601] opened 2017-03-21 17:56 UTC
Hi!

I've upgraded to rails 5.0.2 (from 4.2.7) and using globalized 5.1.0.beta1

When I run `rake assets:precompile` in production mode it throws the error `PG::ConnectionBad: could not connect to server: Connection refused`

And the culprit for what I could find by now is `check_columns!` at https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L49

Is it supposed to run on precompile? What I find odd is that the older version of globalized didn't had this behaviour.

I'm trying now to create a minimal app to reproduce the issue.

**Comment by ismaelga** [comment] 2017-03-21 18:49
Here is an example app: https://github.com/ismaelga/globalized_error_example

I've found that it happens if using models on a initializer.

My temporary solutions for now is using this everywhere 😞 
```ruby
unless ENV['LETMECOMPILETHIS']
  translates :name
end
```

**Comment by ridiculous** [comment] 2017-03-21 20:57
I think the bigger question is, why can't your app talk to the database during that rake task? Is it because the RAILS_ENV is not yet?

**Comment by ismaelga** [comment] 2017-03-21 23:57
@ridiculous It can't because it's running on a docker image build and at that point I don't even have a DB.
RAILS_ENV is set to production.

I think this is new behaviour in latest Globalize version because I could do this just fine with rails 4.2.7 + globalize 5.0.1

**Comment by ismaelga** [comment] 2017-03-22 00:09
I'm pretty sure this issue appeared  here: https://github.com/globalize/globalize/commit/465566fa64270d5cdaae9767d53e813d818f68f0 

And then https://github.com/globalize/globalize/commit/5a41f9ffd034a8f43ba30ccf58a4ceac45c3b56f added a clause to not warn if table does not exists. Maybe there should be another clause that first checks if there's a DB connection? 😕

**Comment by shioyama** [comment] 2017-03-22 00:16
I think the problem is [here](https://github.com/globalize/globalize/blob/e1cbe4247458c13b344738a682609d23eba53f65/lib/globalize/active_record/act_macro.rb#L43) where we check if the table exists. We could add a check about db connections.

**Comment by ismaelga** [comment] 2017-03-22 00:34
Calling `connected?` on those 2 lines should be enough

**Comment by shioyama** [comment] 2017-03-22 00:35
If you could make a PR for that we could merge it very quickly :smile:

**Comment by ismaelga** [comment] 2017-03-22 00:39
Will do 😃

**Comment by parndt** [comment] 2017-04-05 23:57
Fixed in #602

**Closed by parndt** 2017-04-05 23:57 UTC
