### ISSUE TITLE
Using #select on ActiveRecord followed by #attributes call returns unexpected result

### ISSUE THREAD

**Issue by dasnotme** [globalize/globalize#424] opened 2015-02-23 17:22 UTC
As an example lets take the following model:

```
class Place < ActiveRecord::Base
	translates :name, :country
end
```

Me expectation was that if I #select by :id attribute the result should not have any information of other attributes (even the translated ones),

```
2.2.0 :001 > place = Place.select([:id]).first

  Place Load (0.8ms)  SELECT  `places`.`id` FROM `places`  ORDER BY `places`.`id` ASC LIMIT 1
 => #<Place id: 1> 

2.2.0 :002 > place

 => #<Place id: 1> 

2.2.0 :003 > place.attributes

  Place::Translation Load (0.9ms)  SELECT `place_translations`.* FROM `place_translations` WHERE `place_translations`.`place_id` = 1
 => {"id"=>1, "name"=>"London", "country"=>"England"}  
```

which is not happening.

Feature or bug?

**Comment by parndt** [comment] 2015-02-23 19:14
Note the extra SQL load, it's not loaded until you invoke some other attribute that is translated.

Can you see a way that we could support your use case (effectively disabling globalize when `select` is used with only non-translated attributes)?

**Comment by dasnotme** [comment] 2015-02-23 20:00
Unfortunately, it won't work if I perform `Place.select([:id, :name]).first.attributes`, which will still produce the same output:

```
=> {"id"=>1, "name"=>"London", "country"=>"England"}  
```

I fixed it by slicing `attributes`, but that's not something that I would like to do with a bigger collection of complex models.

Is there a way to make Globalize aware of selected attributes?

**Comment by parndt** [comment] 2015-02-23 20:01
I don't know offhand, I haven't looked at the implementation of `select` to determine what happens.

**Comment by shioyama** [comment] 2016-10-01 13:28
I believe this is caused by having the same column name (`name`) on both the model table and translation table. @dasnotme can you confirm? If so I will close this, since we do not support that configuration.

**Comment by shioyama** [comment] 2016-10-01 13:30
Sorry maybe not related to the column issue, but also not something we are probably going to get around to dealing with. Closing this.

**Closed by shioyama** 2016-10-01 13:30 UTC
