### ISSUE TITLE
Undefined method 'type_cast_from_database'

### ISSUE THREAD

**Issue by jdbwin** [globalize/globalize#502] opened 2016-04-26 02:40 UTC
Hi guys,

I am trying out Globalize with Rails5. I created a fresh Rails app with sqlite3.

I reference Globalize master in my Gemfile like so:

`gem "globalize", git: "https://github.com/globalize/globalize", branch: "master"`

I include activemodel-serializers:
`gem 'activemodel-serializers-xml'`

Model:

```ruby
class User < ApplicationRecord
  translates :name
end
```

Migration:

```ruby
class CreateUsers < ActiveRecord::Migration[5.0]
  def up
    create_table :users do |t|
      t.timestamps
    end
    User.create_translation_table! name: :string
  end

  def down
    drop_table :users
    User.drop_translation_table!
  end
end
```

Next, I drop into the Rails console and:

`user = User.new(name: "CoolUser")`

I am met with NoMethodError:

```
NoMethodError: undefined method `type_cast_from_database' for #<ActiveRecord::ConnectionAdapters::Column:0x000000055a49c0>
```

Thanks for your time!

**Comment by jdbwin** [comment] 2016-04-26 04:11
Looks like `type_cast_from_database`, and similar, were removed in  [rails/rails@b93b39e](https://github.com/rails/rails/commit/b93b39eff6829ee05ffec1cc8c505f69cbb53fdc)

**Comment by jdbwin** [comment] 2016-04-26 06:13
I created pr #503 with a quick fix but will wait to open until #501 is passing.

**Comment by iFurt** [comment] 2016-05-16 07:59
Hello everyone! Im still getting this error: 
NoMethodError: undefined method `type_cast_from_database' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f90a1e661b0>

When using default locale (:en) everything works fine, but when I change it I18n.locale = :es , and call for translations - I get error

**Comment by BrahimDa** [comment] 2016-05-18 09:56
hi guys,
is there any fix for that??  i still getting this error.

**Comment by j4rs** [comment] 2016-05-18 13:17
@BrahimDa - I guess the question is when @jdbwin PR will be merged. In the meantime in order to advance you can always ref @jdbwin branch `type_cast_fix_rails5`in your gem.

**Comment by Blazy7** [comment] 2016-05-21 11:06
Hello,
after referring type_cast_fix_rails5@jdbwin branch i get another error:
```
     NoMethodError:
       undefined method `number?' for #<ActiveRecord::ConnectionAdapters::Column:0x007f97f80a9410>
```
Looks like #number? is removed in Rails 5 - [https://github.com/rails/rails/commit/b93b39eff6829ee05ffec1cc8c505f69cbb53fdc#diff-2524057922ad16b58e6b18b2f35b5de2R17](url)

Does anyone know how to fix that?

**Comment by jdbwin** [comment] 2016-05-24 16:24
@Blazy7 pushed a [quick fix](https://github.com/jdbwin/globalize/commit/ab9c3dfee2d4c9537335ff1de63ed2884f24bf2c) to master of my branch of Globalize

**Comment by barnaclebarnes** [comment] 2016-05-29 07:08
@jdbwin Looks like #501 has been merged. Care to reopen your PR?

**Comment by webzorg** [comment] 2016-06-14 10:15
I have `gem "globalize", git: "https://github.com/globalize/globalize", branch: "master"` but still get that error. what should I do with the "fix" links you guys posted?

**Comment by Blazy7** [comment] 2016-06-20 11:51
@webzorg change provided globalize line in your current gemfile with
`gem 'globalize', github: "jdbwin/globalize", :ref => "8857eaf44171dd09e0e7132833cb27d4ac3c569c"`

**Comment by hieuns** [comment] 2016-06-24 01:28
@jdbwin The pull request https://github.com/globalize/globalize/pull/501 has been merged, can you please reopen your PR?

**Comment by jdbwin** [comment] 2016-06-24 02:00
@hieuns Hey there, sorry about that. Been very busy. Will reopen tonight

**Comment by hieuns** [comment] 2016-06-24 02:51
@jdbwin Great! Thank you very much  :thumbsup:

**Comment by shioyama** [comment] 2016-10-05 13:44
Trying to figure out what's going on with this issue. `type_cast_from_database` no longer appears in the latest globalize code, it was taken out in #485 which was merged on April 21st, so I don't understand why everyone here is still reporting the issue.

If you are using the *latest* on `master` I don't see how this issue could still be happening, and I can't reproduce anything like it. Can someone confirm that it is fixed? We'd like to releast 5.1.0 and this is the last rails5 related bug I can find in the issues.

**Comment by dalpo** [comment] 2016-10-06 10:33
@shioyama The issue was affecting a my personal project too, but with merge of #485 now has been definitively resolved.

So I think we can close this issue :wink:

**Comment by shioyama** [comment] 2016-10-06 11:26
@dalpo great thanks! Closing then :smile:

**Closed by shioyama** 2016-10-06 11:26 UTC
Labels: bug, rails5
