### ISSUE TITLE
Bug with duplicate empty field-translation 

### ISSUE THREAD

**Issue by lorenso** [globalize/globalize#371] opened 2014-10-01 10:20 UTC
```
class Question < ActiveRecord::Base
  translates :question, fallbacks_for_empty_translations: true
  globalize_accessors
end

Question.create question_en: 'En',
                question_de: 'De',
                question_se: '' # blank

Question.first.question # 'En'
Question.first.question_en # 'En'
Question.first.question_de # 'De'
Question.first.question_se # '' # good

clone = Question.first.dup

clone.question # 'En'
clone.question_en # 'En'
clone.question_de # 'De'
clone.question_se # 'De' # bad - not blank
```

Why?

**Comment by shioyama** [comment] 2016-10-01 14:13
This looks like it's a question for [globalize-accessors](https://github.com/globalize/globalize-accessors), closing.

**Closed by shioyama** 2016-10-01 14:13 UTC

**Comment by huijar** [comment] 2016-12-07 11:31
For anyone else coming across this issue: I don't think this has anything to do with globalize_accessors. The `initialize_dup` instance method uses `globalize.fetch` when initializing the duplicate. `globalize.fetch` uses fallbacks, which means that the duplicated translation may include fallbacks from other translations. 

https://github.com/globalize/globalize/blob/v5.0.1/lib/globalize/active_record/instance_methods.rb#L104

I don't have the time to write steps to reproduce (basically the same as https://github.com/globalize/globalize/issues/371#issue-44548594 but without globalize_accessors) or submit a PR, but here's what I did: I monkey-patched `initialize_dup` to just duplicate the translations as they are. This works for us, but not necessarily everyone:

```ruby
module Globalize
  module ActiveRecord
    module InstanceMethods
      def initialize_dup(other)
        super
        other.translations.each do |t|
          self.translations << t.dup
        end
      end
    end
  end
end
```

Add that to a file under lib/ and then require the patch in an initializer (`config/initializers`) (preferred) or in `environment.rb`.
