### ISSUE TITLE
Bug in Rails 4 when using translate in combination with serialize

### ISSUE THREAD

**Issue by samu** [globalize/globalize#472] opened 2015-11-04 10:07 UTC
In our app we have two models `A` and `B`, both having a column `data` which is a translated attribute. In addition to that, `B` also serializes the `data` column: 

``` ruby
class A < ActiveRecord::Base
  translates :data
end

class B < ActiveRecord::Base
  serialize :data, Hash
  translates :data
end
```

We run into some really strange behaviour: The configuration of `B` seems to affect `A`, because when we try to save an `A` instance to the database, we get the following error: 

`ActiveRecord::SerializationTypeMismatch (Attribute was supposed to be a Hash, but was a String. ... )` 

`A` isn't supposed to be serializing anything, so it looks like the configuration on `B` is messing up `A`.

The problem goes away if we remove the `translate` configurations on both Models.

**Comment by samu** [comment] 2015-11-05 09:15
I created a repo demonstrating the problem:

https://github.com/samu/translates-and-serialize

It needs to be run in production mode, otherwise the problem does not occur:

`SECRET_KEY_BASE=abc rails s -e production`

Going to the `/dogs` route and creating a new dog throws this error

`ActiveRecord::SerializationTypeMismatch (Attribute was supposed to be a Hash, but was a String. -- "test")`

However, it's the cat model that is configured to serialize the `data` attribute.

**Comment by samu** [comment] 2015-11-06 11:51
I did some further investigation on this. I reproduced the error in the tests. The tests on this branch fail:
https://github.com/globalize/globalize/compare/master...samu:failing-tests

I was able to make the tests succeed again by reverting the following commit by @simi: 
https://github.com/globalize/globalize/commit/47ffb2d8e5b822c1a6743e8304b4c530235ac135

Here's the branch with the commit reverted:
https://github.com/globalize/globalize/compare/master...samu:resolved-tests

I'm not sure how to fix this properly as my understanding for ActiveRecord and globalize is sparse. Please advise. Thank you!

**Comment by acaron** [comment] 2015-11-13 13:26
+1 I get this bug too! But using serialize OpenStruct

**Comment by acaron** [comment] 2015-11-13 13:42
Quick note, there's a patch about it so it must be a known problem: https://github.com/globalize/globalize/blob/master/lib/patches/active_record/serialization.rb

**Comment by simi** [comment] 2015-11-13 13:51
That patch was applied to fix another bug and was just a workaround to store `globalize_serialized_attributes`. Since it was "monkey patch", it is probably not working right now. Let me inspect.

**Comment by acaron** [comment] 2015-11-13 14:03
There's no problem to read the OpenStruct, but it saves it as a string instead. If it can help!

**Comment by samu** [comment] 2015-11-13 15:50
@simi thanks a ton for looking into it, this is currently messing up our production pretty bad.

**Comment by samu** [comment] 2015-11-17 10:59
@simi any updates? i'm happy to implement a fix myself, but i need some help. 

As mentioned above, the bug is fixed on this branch: https://github.com/globalize/globalize/compare/master...samu:resolved-tests

But i don't understand exactly what the commit that i reverted there meant. 

Please help :sun_with_face:

**Comment by acaron** [comment] 2015-12-07 19:53
@samu @simi any updates?

**Comment by simi** [comment] 2015-12-07 20:24
@samu @acaron ok, time to fix this finally. Can you please modify this [template](https://github.com/globalize/globalize/blob/094d152034e2f80a2a93d2dd8f42e7546ea4bd10/issue_template.rb) to reproduce your exact problems?

**Comment by acaron** [comment] 2015-12-08 02:00
@simi only serialize content with OpenStruct.

`Post.create(content: OpenStruct.new(value: 'foobar'))``

`content` return a string with `#OpenStruct...` instead of an OpenStruct instance.

```
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
gem 'globalize', '5.0.1'
require 'active_record'
require 'globalize'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :post_translations, force: true do |t|
    t.references :post
    t.string     :title
    t.text       :content
    t.string     :locale
  end
end

class Post < ActiveRecord::Base
  translates :content, :title

  serialize :content, OpenStruct
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: 'HI')

    assert_equal 'HI', post.title
  end
end
```

**Comment by samu** [comment] 2015-12-08 07:10
I reproduced the problem as mentioned [here](https://github.com/globalize/globalize/issues/472#issuecomment-154392022)

**Comment by acaron** [comment] 2015-12-08 13:31
@samu I tried your branch and it didn't solve my case

**Comment by mvz** [comment] 2016-02-23 15:53
It looks like the bug here was introduced in b50e250266b5357d0193e7a5d9030917a1543980, where the `mattr_accessor` was moved to `ActiveRecord::Base`. Since these attributes are shared with subclasses, this has the disastrous effect of sharing the list of serialized attributes among all models.

So, it is not necessary to revert 47ffb2d8e5b822c1a6743e8304b4c530235ac135, but instead a non-shared class attribute should be used.

**Comment by markdavies** [comment] 2017-01-12 00:14
Any plan to fix this? It's caused us a big headache over the last week. The update made by @ebeigarts works really well and should probably be merged.

**Comment by ouranos** [comment] 2017-08-10 06:54
Same here, any plans to merge #499?

**Comment by parndt** [comment] 2017-08-10 14:02
FYI @ouranos @indirect @samu @markdavies etc this is merged now 😄

**Closed** 2017-08-10 14:01 UTC
Labels: bug
