### ISSUE TITLE
Rails 4.2.3, Psql and globalize 5.01 find_by query broke

### ISSUE THREAD

**Issue by krisdigital** [globalize/globalize#458] opened 2015-08-17 07:05 UTC
Same as: https://github.com/globalize/globalize/issues/423

Hi,

after upgrading to globalize 5.0 and rails 4.2.3, there is a strange error with find_by queries.

Doing something simple as

```ruby
Category.find_by(name: "Name of the category")
```

results in the following query:
```SQL
Category Load (3.1ms)  SELECT  "categories".* FROM "categories" INNER JOIN "category_translations" ON "category_translations"."category_id" = "categories"."id" WHERE "category_translations"."name" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' AND "category_translations"."locale" = $1 LIMIT 1  [["locale", "de"]]
```

I searched around already but could not find anything, so maybe someone knows a solution. It worked flawlessly before.

```ruby
create_table "categories", force: :cascade do |t|
    t.string   "name",       limit: 255
    t.integer  "parent_id"
    t.integer  "lft"
    t.integer  "rgt"
    t.integer  "depth"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

create_table "category_translations", force: :cascade do |t|
    t.integer  "category_id",             null: false
    t.string   "locale",      limit: 255, null: false
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name",        limit: 255
  end

```

Thanks in advance!

P.S. Normal find(id) queries are working as usual.

**Comment by FunkyloverOne** [comment] 2015-08-25 07:02
Hi, I guess you should use this:

Category.includes(:translations).find_by(name: "Name of the category")

find(id) queries are working as usual because you aren't translating the id field.

**Comment by krisdigital** [comment] 2015-08-25 16:11
@FunkyloverOne Hi, thank you for your tip! I already use and posted this solution https://github.com/globalize/globalize/issues/423#issuecomment-133725817

That way you do not have to change all places in your code where you use find_by queries..

**Comment by FunkyloverOne** [comment] 2015-08-26 06:22
@krisdigital cool! I wasn't too attentive, thanks :)

**Comment by shioyama** [comment] 2016-10-01 13:06
Ok, after fiddling for a while, I can reproduce this. The reason it is happening is that you use `name` in *both* the `places` table *and* the `place_translations` table. I don't believe we have a note about this anywhere but generally **you should not do this**. I think we once had a spec to check that Globalize will handle the situation gracefully, but it's gone and generally we assume your model does not have the same column in both tables, because it will definitely screw things up.

I'll leave this open for now, but I don't consider this easily fixable. Removing the column on the `places` table should fix the issue.

**Comment by krisdigital** [comment] 2016-10-02 10:36
Hi @shioyama ,

thank's for pointing that out! As you can see from my scheme posted above I have the name column in both tables! If that is the problem, maybe one should delete the original column at the end of the globalize migration? I think in most case people setup their translations that way, but I may be wrong..

**Comment by shioyama** [comment] 2016-10-02 10:59
@krisdigital Ah, this explains why so many people have this configuration! The migration script does not remove or at least rename the original column. I'll change the script so that it renames the original column something else at least so the data remains but doesn't interfere with activerecord queries, etc.

For now, to solve the issue, just add a migration either removing the original column, or renaming it.

**Comment by shioyama** [comment] 2016-10-02 11:02
Created an issue for it in #558. I'm going to close this, @krisdigital let me know if you still see the issue after renaming/removing the column on the model table.

**Closed by shioyama** 2016-10-02 11:02 UTC
Labels: bug

**Comment by krisdigital** [comment] 2016-10-02 11:45
@shioyama Great, thank's for looking into it!
