### ISSUE TITLE
undefined method type_cast_from_database

### ISSUE THREAD

**Issue by folivi** [globalize/globalize#522] opened 2016-06-26 23:40 UTC
Hi,
I just run into this issue when trying to use globalize in my rails5 app:

undefined method `type_cast_from_database' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f956355d520>

in the place form this line is highlighted:

 <%= f.text_field :name %>

Here goes my implementation:

My Place model:

```
class Place < ApplicationRecord
	translates :name, :description, :short_description, :slug
	#extend FriendlyId

	#friendly_id :name, use: [:slugged, :finders, :globalize]
end

```

The migration:

```
class CreatePlaces < ActiveRecord::Migration[5.0]
  def up
    create_table :places do |t|
      t.string :name
      t.string :short_description
      t.text :description
      t.string :city
      t.float :longitude
      t.float :latitude

      t.string :slug

      t.timestamps
    end
    Place.create_translation_table! name: :string, short_description: :string, description: :text, slug: :string
  end

  def down
    drop_table :places
    Place.drop_translation_table!
  end

  
end
```

gemfile:
gem 'rails', '>= 5.0.0.rc1', '< 5.1'
gem 'pg', '~> 0.18'
gem 'globalize', git: 'https://github.com/globalize/globalize', branch: 'master'
gem 'activemodel-serializers-xml'
gem 'friendly_id', '~> 5.1.0'
gem 'friendly_id-globalize'

What I'm I missing here?

**Comment by programmingJOJO** [comment] 2016-06-30 12:42
Perhaps this issue is similar to https://github.com/globalize/globalize/issues/502?

**Comment by parndt** [comment] 2016-07-05 09:36
Is this still an issue ?

**Comment by folivi** [comment] 2016-07-06 05:11
hey gys,
I'll try it and get back to you before the end of the day

2016-07-05 12:36 GMT+03:00 Philip Arndt <notifications@github.com>:

**Comment by shioyama** [comment] 2016-10-02 08:50
This looks like a duplicate of #502, closing. @programmingJOJO if this is a different issue, please feel free to re-open it.

**Closed by shioyama** 2016-10-02 08:50 UTC
Labels: bug, rails5
